language: python
matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5


before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda update --yes conda
    # This help testing code with pylab
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"


install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy pyparsing scipy matplotlib nose pandas nose
  - pip install nose coverage
  - pip install coveralls
# # command to run tests, e.g. python setup.py test
script:
  - python setup.py nosetests --with-coverage --cover-package fitter

after_success:
  coveralls
